site_name: Impeller

theme:
  name: material
  logo: assets/impeller_white.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.expand
    - navigation.top
    - navigation.sections
    - content.code.copy
    - content.action.view
    - content.tabs.link
    - toc.follow
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - offline
  - search

edit_uri: edit/main/docs/

repo_url: https://github.com/flutter/engine
repo_name: flutter/engine

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
      title: On this page
